### ISSUE TITLE
Current dir is added to PYTHONPATH

### ISSUE THREAD

**Issue by edevil** [gabrielelanaro/emacs-for-python#95]
I started having problems when opening files like https://github.com/pycassa/pycassa/blob/master/pycassa/columnfamily.py

In that dir is a file called types.py. When I open columnfamily.py in Emacs flymake throws an error and stops working. Debugging this problem showed that the current dir is added to PYTHONPATH, and when this happens:

```
$ PYTHONPATH=. pyflakes columnfamilymap.py
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site.py", line 62, in <module>
    import os
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 49, in <module>
    import posixpath as path
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 17, in <module>
    import warnings
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/warnings.py", line 8, in <module>
    import types
  File "./types.py", line 7, in <module>
    import random
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/random.py", line 43, in <module>
    from warnings import warn as _warn
```

Is "emacs-for-python" responsible for this?

**Comment by piotr-dobrogost** [comment]
I think `PYTHONPATH` has nothing to do with it.

From https://docs.python.org/2/library/sys.html

> As initialized upon program startup, the first item of this list, path[0], is the directory containing the script that was used to invoke the Python interpreter. If the script directory is not available (e.g. if the interpreter is invoked interactively or if the script is read from standard input), path[0] is the empty string, which directs Python to search modules in the current directory first

**Comment by xgoeforever** [comment]
i got the same question and the way help me,but i want know Y,who can help me.
